development:
  solr:
    hostname: localhost
    port: 8683
    log_level: INFO
    solr_home: solr
    path: /solr/development

production:
  solr:
    hostname: localhost
    port: 8683
    log_level: WARNING

test:
  solr:
    hostname: localhost
    port: 8681
    log_level: WARNING