site_url: <%= ENV['SITE_URL'] || "http://nreduce-josh.herokuapp.com" %>
email_host: "nreduce.com"
screenr_recorder_id: 'xxxxxxx'

apis:
  linkedin:
    key: <%= ENV['LINKEDIN_API_KEY'] %>
    secret_key: <%= ENV['LINKEDIN_API_SECRET'] %>

  twitter:
    consumer_key: ""
    consumer_secret: ""
    oauth_token: ""
    oauth_token_secret: ""

  mailchimp:
    enabled: true
    api_key: ""
    everyone_list_id: ""
    startup_list_id: ""
    mentor_list_id: ""
    investor_list_id: ""

smtp_settings:
  address: 'smtp.sendgrid.net'
  port: 587
  domain: ''
  user_name: ''
  password: ''
  authentication: 'plain'
  enable_starttls_auto: true
